### GET table
Get http://localhost:3001

### Add new table
POST http://localhost:3001/new HTTP/1.1
Content-Type: : application/json


{
    "Email": "test@gmail.com",
    "username": "velhotest",
    "password": "test1234"
}
